# Generated by Django 3.1.6 on 2021-11-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_chat_chatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='messages',
            field=models.TextField(),
        ),
    ]
