# Generated by Django 3.1.6 on 2021-10-22 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20211022_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='friend',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
