# Generated by Django 3.1.6 on 2021-11-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211123_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='messages',
            new_name='message',
        ),
    ]
