# Generated by Django 3.1.6 on 2021-11-24 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211124_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='room',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='timestamp',
        ),
    ]
