# Generated by Django 3.1.6 on 2021-12-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211124_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='members',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
