# Generated by Django 3.1.6 on 2021-12-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211209_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='host',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
